
puts "DIGITE O VALOR DE RAIO DA CINCUNFERENCIA  : "
RAIO = gets.chomp.to_f
puts ""


#### CALCULO DE AREA DE CIRCUNFERENCIA #####
AREA = (3.14159265 * RAIO ** 2)

puts " VALOR DA AREA DE CIRCUNFERENCIA #{AREA}"
